name: main

run-name: ${{ github.event.client_payload.title }} - ${{ github.event.client_payload.repo }}

on:
  repository_dispatch:
    types: [labeled-issue]

jobs:
  sync-github-issue-to-notion:
    runs-on: ubuntu-latest
    name: Create Notion Ticket
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - name: Extract repository name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV
      - name: Sync GitHub Issue to Notion
        uses: './notion-action'
        with:
          notion_token: ${{ secrets.NOTION_TOKEN }}
          notion_task_database_id: ${{ secrets.NOTION_TASK_DATABASE_ID }}
          title: ${{ github.event.client_payload.title }}
          url: ${{ github.event.client_payload.url }}
          repo_name: ${{ env.REPO_NAME }}
          repo_owner: ${{ github.event.client_payload.repo_owner }}